-- NOTICES TABLE
CREATE SEQUENCE auto_notices_increment_seq;
CREATE TABLE NOTICES (
INDEX INT NOT NULL DEFAULT nextval('auto_notices_increment_seq'::regclass) primary key,
TITLE VARCHAR(80) NOT NULL,
WRITER VARCHAR(50) NOT NULL,
CONTENT TEXT,
HITCOUNT INT DEFAULT 0,
REGIDATE DATE NEW()
);

-- NOTICE_FILES TABLE
CREATE SEQUENCE auto_notice_files_increment_seq;
CREATE TABLE 

CREATE SEQUENCE auto_notice_files_increment_seq;
CREATE TABLE NOTICE_FILES (
FILENO INT NOT NULL DEFAULT nextval('auto_notices_increment_seq'::regclass) primary key,
INDEX INT NOT NULL,
PATH VARCHAR(250) NOT NULL,
FILENAME VARCHAR(200) NOT NULL
);